-- MySQL Script generated by MySQL Workbench
-- Mon Feb  7 16:45:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alkemy_disney
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alkemy_disney` ;

-- -----------------------------------------------------
-- Schema alkemy_disney
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkemy_disney` DEFAULT CHARACTER SET utf8 ;
USE `alkemy_disney` ;

-- -----------------------------------------------------
-- Table `alkemy_disney`.`characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_disney`.`characters` ;

CREATE TABLE IF NOT EXISTS `alkemy_disney`.`characters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` VARCHAR(150) NULL DEFAULT NULL,
  `edad` INT NULL DEFAULT NULL,
  `peso` DECIMAL(10,2) NULL DEFAULT NULL,
  `historia` VARCHAR(200) NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `updatedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `alkemy_disney`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_disney`.`genres` ;

CREATE TABLE IF NOT EXISTS `alkemy_disney`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `updatedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `alkemy_disney`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_disney`.`movies` ;

CREATE TABLE IF NOT EXISTS `alkemy_disney`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `calificacion` INT NULL DEFAULT NULL,
  `genre_id` INT NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `updatedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `genre_id_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `alkemy_disney`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `alkemy_disney`.`character_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_disney`.`character_movie` ;

CREATE TABLE IF NOT EXISTS `alkemy_disney`.`character_movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NULL DEFAULT NULL,
  `character_id` INT NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `updatedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `character_id_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `character_id`
    FOREIGN KEY (`character_id`)
    REFERENCES `alkemy_disney`.`characters` (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `alkemy_disney`.`movies` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `alkemy_disney`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_disney`.`users` ;

CREATE TABLE IF NOT EXISTS `alkemy_disney`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `updatedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
